language: cpp
compiler:
    - gcc
os:
    - linux
before_install:
    - MINICONDA_VERSION=latest
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then MINICONDA_PY=2; else MINICONDA_PY=3; fi
    - wget https://repo.anaconda.com/miniconda/Miniconda$MINICONDA_PY-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p "$HOME"/miniconda
    - source "$HOME"/miniconda/etc/profile.d/conda.sh
    - hash -r 
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels conda-forge
    - conda update -q conda
    - conda install conda-build
    - conda info -a
    - export LANG=en_US.UTF-8
install:
    - git clone --depth=1 https://github.com/straten/epsic.git
    # Could get the number of commits on a given date like:
    # git -C epsic log --format="%cd" --date=short | uniq -c | head -n1
    # Then split it up inside the meta.yaml.
    - export VERSION=$(git -C ./epsic log -1 --format='%cd' --date=short | sed 's/-/./g')
    - conda build recipe
    - conda activate
    - conda install epsic --use-local
script:
    - epsic
